### ISSUE TITLE
The entity name must immediately follow the '&' in the entity reference

### ISSUE THREAD

**Issue by justodepp** [hyperdevs-team/poeditor-android-gradle-plugin#66]
- Plug-in Version 3.4.0

As for the title the error message it's the same 

> "The entity name must immediately follow the '&' in the entity reference"

tested also on version 3.3.1 and this version doesn't have this issue.

Thanks

**Comment by adriangl** [comment]
Hi @justodepp!
Do you have any sample string that I can use to reproduce the error?

Thanks!

**Comment by justodepp** [comment]
Hi Adrían,
sure here one for example, "T &amp; C"
this one is inside the project the one coming from POEditor it's just
something like this "T & C"

Saluti
*Gianni Andrea Cavalli*


Il giorno gio 18 mag 2023 alle ore 17:40 Adrián García <
***@***.***> ha scritto:

**Comment by carlosrivin** [comment]
Had the same issue just now. Because of the same string :)

**Comment by adriangl** [comment]
Hey @justodepp @carlosrivin! Sorry for replaying so late.
I've been testing version 3.4.1 of the plug-in with these strings:
```xml
    "test_issue_66_1" -> "T&C"
    "test_issue_66_2" -> "T & C"
    "test_issue_66_3" -> "T &amp; C"
```

and got the following results:
```xml
    <string name="test_issue_66_1">"T&amp;C"</string>
    <string name="test_issue_66_2">"T &amp; C"</string>
    <string name="test_issue_66_3">"T &amp;amp; C"</string>
```

These should be the proper escape sequences so I believe the plugin is working as expected. Does the error happen when using the plugin or when compiling your apps?

**Comment by bogdanzurac** [comment]
We've had the same issue in one of our own projects. 
PoEditor CMS contains the following string:
<img width="753" alt="image" src="https://github.com/hyperdevs-team/poeditor-android-gradle-plugin/assets/3236878/88b2b0f7-f137-49e9-ab67-68289bc8ce44">

When using this config (which doesn't specify the `unescapeHtmlTags` field), we get the error:
```
poEditor {
    apiToken.set("xxx")
    projectId.set(123)
    order.set("terms")
    tags.set(listOf("android", "app"))
    unquoted.set(true)
}
```

However, when turning `unescapeHtmlTags` to `false`, it works without any issues:
```
poEditor {
    apiToken.set("xxx")
    projectId.set(123)
    order.set("terms")
    tags.set(listOf("android", "app"))
    unquoted.set(true)
    unescapeHtmlTags.set(false)
}
```

`<string name="puf_details_solutions">Common problems &amp; solutions</string>`

This happens because the default value of `unescapeHtmlTags` is `true`. It seems rather confusing that we need to toggle the default value of the `unescapeHtmlTags` field in order to affect ampersand parsing, as it should work regardless of this config value.


A related problem is that when using `unescapeHtmlTags` set to `false`, we get HTML strings like this:

`<string name="puf_details_report">Report a &lt;a href=\"https://www.google.com\"&gt;problem&lt;/a&gt;</string>`

Which are not wrapped in a `<![CDATA[ ... ]]` block, hence are not handled properly on Android. Should this be reported as a separate bug?

**Comment by nokite** [comment]
This started happening in our project when we updated:
from AGP 4.2.2 + gradle 6.9 + java 8
to AGP 8.3.0 + gradle 8.4 + java 17 (build), java 11 (source)

It happens both with plugin version 3.4.2 and 4.2.0.

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 1601; columnNumber: 59; The entity name must immediately follow the '&' in the entity reference.
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
        at com.hyperdevs.poeditor.gradle.ktx.DocumentExtensionsKt.toStringsXmlDocument(DocumentExtensions.kt:41)
        at com.hyperdevs.poeditor.gradle.xml.XmlPostProcessor.splitTranslationXml(XmlPostProcessor.kt:113)
        at com.hyperdevs.poeditor.gradle.xml.XmlPostProcessor.postProcessTranslationXml(XmlPostProcessor.kt:55)
        at com.hyperdevs.poeditor.gradle.PoEditorStringsImporter.importPoEditorStrings(PoEditorStringsImporter.kt:146)
        at com.hyperdevs.poeditor.gradle.tasks.ImportPoEditorStringsTask.importPoEditorStrings(ImportPoEditorStringsTask.kt:184)

```

Nice that `unescapeHtmlTags = false` fixes the issue. It introduces some other changes though. Some seem fine, so can be problematic.

This seems fine - it changes emoji codes/formats, but they still work. 
For instance, it changes this string `&#x1f929;` into `&#129321;`. Both resolve to the same emoji - 🤩. The first one is the emoji Hex code point (as it was originally, before upgrading AGP, gradle and Java). The second one is the Decimal code point of the same emoji.

**This does not seem fine though** - it encodes tags, so they don't work anymore. For instance, it breaks tags like <b>. 
You might be using this tag to make text bold in the Android UI (works even in Toast messages). For instance: `John is \"<b>awesome</b>\", really!` to output "John is "**awesome**", really!", it will be broken when using `unescapeHtmlTags = false`: `John is \"&lt;b&gt;awesome&lt;/b&gt;\", really!` - which appears exactly like that in the UI.

**Comment by LightWeek** [comment]
Having the same exact issue.
Plugin version: 4.2.0
The term in POEditor is:
<img width="287" alt="image" src="https://github.com/hyperdevs-team/poeditor-android-gradle-plugin/assets/99963267/e10e56cb-a4d5-4152-b65b-ea96ebe8f54b">

`Enable Alarm & Reminders` - issue reproduces, gradle task fails
`Enable Alarm &amp; Reminders` - task succeeds, the result is "**Enable Alarm & Reminders**" (& breaks Android strings in that case)
`Enable Alarm &amp;amp; Reminders`- task succeeds, produces correct Android string: "**Enable Alarm &amp; Reminders**"

**Comment by adriangl** [comment]
Sorry, I haven't got much time to work on the plug-in as much as I'd like apart from merging some PRs and critical bugfixes.  However, I managed to give this a run.

I've been checking the `unescapeHtmlTags` and it's original purpose (to unescape HTML tags present in strings, so they can be autoformatted in code). Right now the code in `unescapeHtmlTags` is the following:

```kotlin
/**
 * Unescapes HTML tags from string.
 */
fun String.unescapeHtmlTags() = this
    .replace("&lt;", "<")
    .replace("&gt;", ">")
    .replace("&amp;", "&")
    .replace("&apos;", "'")
    .replace("&quot;", "\"")
```

Thinking about this, it would make sense to just replace what is needed for this: `<` and `>` and remove the rest of HTML entities management from here: that way `&`s will always be translated to `&amp;` (as PoEditor export them in XML) and the issue should no longer happen. I'll try fixing this as soon as I can :)
